import '@pages/glavnaya.ejs';
import '@pages/instruction.ejs';
import '@pages/dostavka_i_oplata.ejs';
import '@pages/vibrat_complekt.ejs';
import '@pages/komplekt.ejs';
import '@pages/detal.ejs';
import '@pages/oformit_zakaz.ejs';
import '@pages/ostavit_otziv.ejs';
import '@pages/politika_konfidenczialnosti.ejs';
import '@pages/o_nas.ejs';
import '@pages/end_payment.ejs';

import '@js/main.js';
import '@scss/main.scss';

import '@product-small-info-block-img/front.jpg';
import '@product-small-info-block-img/back.jpg';
import '@product-small-info-block-img/search-overlay.jpg';
import '@product-small-info-block-img/instruction.jpg';
import '@product-small-info-block-img/bagazhnik.svg';
import '@product-small-info-block-img/fary.svg';
import '@product-small-info-block-img/kapot.svg';
import '@product-small-info-block-img/krylya.svg';
import '@product-small-info-block-img/krysha.svg';
import '@product-small-info-block-img/peredniye-stoyki.svg';
import '@product-small-info-block-img/ruchki.svg';

// import '@img/media-test/test.svg';

// import '@img/media-test/obrabotka_salona_3-1.jpg';
// import '@img/media-test/obrabotka_salona_3-1-300x171.jpg';
// import '@img/media-test/obrabotka_salona_3-1-400x229.jpg';
// import '@img/media-test/obrabotka_salona_3-1-500x286.jpg';
// import '@img/media-test/obrabotka_salona_3-1-600x343.jpg';
// import '@img/media-test/obrabotka_salona_3-1-700x400.jpg';
// import '@img/media-test/obrabotka_salona_3-1-800x457.jpg';
// import '@img/media-test/obrabotka_salona_3-1-900x514.jpg';
// import '@img/media-test/obrabotka_salona_3-1-1000x571.jpg';
// import '@img/media-test/obrabotka_salona_3-1-1100x629.jpg';
// import '@img/media-test/obrabotka_salona_3-1-1200x686.jpg';
// import '@img/media-test/obrabotka_salona_3-1-1300x743.jpg';
// import '@img/media-test/obrabotka_salona_3-1-1400x800.jpg';
// import '@img/media-test/obrabotka_salona_3-1-1600x914.jpg';
// import '@img/media-test/obrabotka_salona_3-1-1800x1029.jpg';
// import '@img/media-test/obrabotka_salona_3-1-2000x1143.jpg';
// import '@img/media-test/obrabotka_salona_3-1-2500x1429.jpg';
// import '@img/media-test/obrabotka_salona_3-1-3000x1714.jpg';
// import '@img/media-test/obrabotka_salona_3-1-4000x2286.jpg';
// import '@img/media-test/obrabotka_salona_3-1-5000x2857.jpg';
// import '@img/media-test/obrabotka_salona_3-1-6000x3429.jpg';
// import '@img/media-test/obrabotka_salona_3-1-7000x4000.jpg';
// import '@img/media-test/obrabotka_salona_3-1-8000x4571.jpg';
